travis:
  secure:
    BINSTAR_TOKEN: QweD1rmED3Jnn5xYVvgyTILjuT8x6kPGMABtmVJXPF4c2h/61jFh8rMptisLSqv0yYHfRG2YWrNTzXrJcBMU1f9101G60YIc/AYiOiwKMGeO/5IAdegAPkZlL/Dxqdh2QLtmn65LE6dLJhavCql5ck2WNCpCgz0fJqXwljDfQohG9ViuPsDS+U2MZIGJrvy0kJhw1CdzpugTX78aJwLpEVQ8+IPAZkD8/Pkyl+VXK1YotP8XxAk3YKvHgL8xctoNv3ZXRhb6Do4KzHvTC8n5315y0HVGQds8SwHPzzPojKyHwmBqnD/QwyhxaWfS5SC9w/mZCB5qn8hk6EXhLn+ESGWRZ99xDXJ9g9VHZOnJh8OI/5UgTKM0Gbxmh5hIqahiy+xyCE1j9MPUxLscPz2jsVdwr/jSE1metDUEOANAyfFkD8F2r1keHqm9C/ydDYnq+2kIa9spMC1+J+uRaFrSKkp+sXcGU3FwNH/xvBUPPs0Lh4PZYJikroXxTsVk1+RK80mDnsGRiP0Spw6VEDfETZBIGBoaSGUUlJknjCEAbrifbkrKUhE55eCVYo0eFrwKjCNQszB3XF3KmtRSev/tnOg8qGKg5VDAw1q2GN3DofoFzdmDbhAXJsyZ0SWyeDiWjEuOEI8zm1RmCQqBGPGMGvIBu1sFcMfl1DwOVnsceNE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
